# Generated by Django 3.2.7 on 2022-06-18 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'asistencia',
                'verbose_name_plural': 'asistencias',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(blank=True, max_length=8, null=True, verbose_name='DNI')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo Electronico')),
                ('cellphone', models.CharField(blank=True, max_length=12, null=True, verbose_name='Celular')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('capacity', models.IntegerField(verbose_name='capacidad')),
                ('min_age', models.IntegerField(verbose_name='edad minima')),
                ('max_age', models.IntegerField(verbose_name='edad maxima')),
            ],
            options={
                'verbose_name': 'clase',
                'verbose_name_plural': 'clases',
            },
        ),
        migrations.CreateModel(
            name='AttendanceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='dashboard.attendance')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.person', verbose_name='niño/a')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.space', verbose_name='clase')),
            ],
            options={
                'verbose_name': 'asistencia detalle',
                'verbose_name_plural': 'asistencias detalles',
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='parent_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_a', to='dashboard.person', verbose_name='deja'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='parent_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_b', to='dashboard.person', verbose_name='recoje'),
        ),
    ]
