# Generated by Django 3.2.7 on 2021-11-26 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8, verbose_name='DNI')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo Electronico')),
                ('cellphone', models.CharField(blank=True, max_length=12, null=True, verbose_name='Celular')),
            ],
            options={
                'verbose_name': 'persona',
                'verbose_name_plural': 'personas',
            },
        ),
        migrations.CreateModel(
            name='ChildSib',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.IntegerField(blank=True, choices=[(1, 'madre'), (2, 'padre'), (3, 'hermano/a'), (4, 'tio/a'), (5, 'abuelo/a'), (6, 'primo/a'), (7, 'sobrino/a')], null=True, verbose_name='relacion')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='dashboard.person', verbose_name='niño/a')),
                ('sib', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sib', to='dashboard.person', verbose_name='pariente')),
            ],
            options={
                'verbose_name': 'pariente',
                'verbose_name_plural': 'parientes',
            },
        ),
        migrations.CreateModel(
            name='AttendanceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.person', verbose_name='niño/a')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='codigo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sib', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.person', verbose_name='pariente')),
            ],
            options={
                'verbose_name': 'asistencia',
                'verbose_name_plural': 'asistencias',
            },
        ),
    ]
