# Generated by Django 3.2.7 on 2022-03-09 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancedetail',
            options={'verbose_name': 'asistencia detalle', 'verbose_name_plural': 'asistencias detalles'},
        ),
        migrations.AlterUniqueTogether(
            name='childsib',
            unique_together={('child', 'sib')},
        ),
    ]
