# Generated by Django 3.2.7 on 2022-06-19 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'persona', 'verbose_name_plural': 'personas'},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='parent_a',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='parent_b',
        ),
        migrations.AddField(
            model_name='attendance',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='dashboard.person', verbose_name='pariente'),
        ),
        migrations.CreateModel(
            name='ChildSib',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_up', models.IntegerField(blank=True, choices=[(1, 'madre'), (2, 'padre'), (3, 'hermano/a'), (4, 'tio/a'), (5, 'abuelo/a'), (6, 'primo/a'), (7, 'sobrino/a'), (8, 'hijo/a'), (9, 'sobrino/a'), (10, 'nieto/a')], null=True, verbose_name='relacion arriba')),
                ('relationship_down', models.IntegerField(blank=True, choices=[(1, 'madre'), (2, 'padre'), (3, 'hermano/a'), (4, 'tio/a'), (5, 'abuelo/a'), (6, 'primo/a'), (7, 'sobrino/a'), (8, 'hijo/a'), (9, 'sobrino/a'), (10, 'nieto/a')], null=True, verbose_name='relacion abajo')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='dashboard.person', verbose_name='niño/a')),
                ('sib', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sib', to='dashboard.person', verbose_name='pariente')),
            ],
            options={
                'verbose_name': 'pariente',
                'verbose_name_plural': 'parientes',
                'unique_together': {('child', 'sib')},
            },
        ),
    ]
