# Generated by Django 3.2.7 on 2022-03-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20220309_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='day_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
    ]
