# Generated by Django 3.2.7 on 2022-06-19 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20220618_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='parent',
        ),
        migrations.AddField(
            model_name='attendance',
            name='parent_a',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parent_a', to='dashboard.person', verbose_name='deja'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='parent_b',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parent_b', to='dashboard.person', verbose_name='recoje'),
            preserve_default=False,
        ),
    ]
