# Generated by Django 3.2.7 on 2022-03-11 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_person_day_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='childsib',
            old_name='relation',
            new_name='relationship',
        ),
    ]
