# Generated by Django 3.2.7 on 2022-03-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_relation_childsib_relationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childsib',
            name='relationship',
        ),
        migrations.AddField(
            model_name='childsib',
            name='relationship_down',
            field=models.IntegerField(blank=True, choices=[(1, 'madre'), (2, 'padre'), (3, 'hermano/a'), (4, 'tio/a'), (5, 'abuelo/a'), (6, 'primo/a'), (7, 'sobrino/a'), (8, 'hijo/a'), (9, 'sobrino/a'), (10, 'nieto/a')], null=True, verbose_name='relacion'),
        ),
        migrations.AddField(
            model_name='childsib',
            name='relationship_up',
            field=models.IntegerField(blank=True, choices=[(1, 'madre'), (2, 'padre'), (3, 'hermano/a'), (4, 'tio/a'), (5, 'abuelo/a'), (6, 'primo/a'), (7, 'sobrino/a'), (8, 'hijo/a'), (9, 'sobrino/a'), (10, 'nieto/a')], null=True, verbose_name='relacion'),
        ),
    ]
