# Generated by Django 3.2.7 on 2022-06-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20220619_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancedetail',
            name='released',
            field=models.BooleanField(default=False),
        ),
    ]
