# Generated by Django 3.2.7 on 2022-07-08 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_attendancedetail_released'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancedetail',
            name='received',
            field=models.BooleanField(default=False),
        ),
    ]
