# Generated by Django 3.2.7 on 2022-03-11 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20220311_0719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='code',
        ),
        migrations.AddField(
            model_name='attendancedetail',
            name='attendance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='dashboard.attendance'),
            preserve_default=False,
        ),
    ]
