# Generated by Django 3.2.7 on 2022-07-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20220720_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='DNI/Carnet Extranjeria'),
        ),
    ]
