# Generated by Django 3.2.7 on 2022-08-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_person_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancedetail',
            name='nro',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='nro'),
        ),
    ]
