# Generated by Django 3.2.7 on 2022-10-19 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_person_lacomu_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='PersonApp',
        ),
    ]
